#pragma config(Motor,  port1,           moGoLeft,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           intakeClaw,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           upperArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lowerArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intakeArm,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           backRight,     tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          moGoRight,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void base();
void arm();
void moGoManip();
void intake();
void claw();

//models a control scheme between 2 buttons to one motor, one for each direction. Returns -1, 0, or 1 given the 2 buttons.
int between(int control1, int control2){
	if(vexRT[control1] ^ vexRT[control2]){
		return vexRT[control1] ? 1 : -1;
	}
	return 0;
}


task main()
{
	int prevBtn8U = 0;
	while(true){
		base();
		arm();
		intake();
		moGoManip();

		if(prevBtn8U==1 && vexRT[Btn8U]==0){
			claw();
		}

		prevBtn8U = vexRT[Btn8U];
	}
}

void base(){
	motor[frontLeft] = vexRT[Ch3];
	motor[frontRight] = vexRT[Ch2];
	motor[backLeft] = vexRT[Ch3];
	motor[backRight] = vexRT[Ch2];
}

void arm()
{
	motor[upperArm] = 127*between(Btn6U, Btn6D);
	motor[lowerArm] = 127*between(Btn6U, Btn6D);
}

void claw(){
	motor[intakeClaw] *= -1;
	if(motor[intakeClaw] == 0){
		motor[intakeClaw] = 50;
	}
}

void moGoManip()
{
	motor[moGoLeft] = 127*between(Btn7U, Btn7R);
	motor[moGoRight] = 127*between(Btn7U, Btn7R);
}

void intake()
{
	motor[intakeArm] = 127*between(Btn5D, Btn5U);

}
